language: elixir
sudo: false
elixir:
  - 1.4
  - 1.5
  - 1.6
  - 1.7
otp_release:
  - 19.3
  - 20.3
  - 21.0
matrix:
  exclude:
    - elixir: 1.4
      otp_release: 21.0
    - elixir: 1.5
      otp_release: 21.0
script:
  - "MIX_ENV=test mix do deps.get, compile, coveralls.travis"
notifications:
  recipients:
    - paulschoenfelder@gmail.com
    - chris@chrishildebrand.net
