language: elixir
sudo: false
elixir:
  - 1.4
  - 1.5
  - 1.6
  - 1.7
otp_release:
  - 19
  - 20
  - 21
script:
  - "MIX_ENV=test mix do deps.get, compile, coveralls.travis"
notifications:
  recipients:
    - paulschoenfelder@gmail.com
