language: elixir
sudo: false
elixir:
  - 1.0.5
otp_release:
  - 17.4
env: MIX_ENV=all
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
notifications:
  recipients:
    - paulschoenfelder@gmail.com
