language: elixir
otp_release:
  - 17.0
  - 17.1
elixir:
  - 1.0.0
env: MIX_ENV=all
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
notifications:
  email:
    - paulschoenfelder@gmail.com
